local _, J = ...
-- Generated by tools/measure_cast_borders.py; original artwork stays unchanged.
-- Transparent inset from each shared slice boundary to the painted rail.
local insets = {
    CLASS_DEATHKNIGHT = {3,7,3,2},
    CLASS_DEMONHUNTER = {9.5,1,9.5,2},
    CLASS_DRUID = {5,12,11.5,3},
    CLASS_EVOKER = {8,3,8,2},
    CLASS_HUNTER = {2,1,2,1},
    CLASS_MAGE = {2,5,3,4},
    CLASS_MONK = {2,2,2,2},
    CLASS_PALADIN = {10,1,10,1},
    CLASS_PRIEST = {23,4,23,2},
    CLASS_ROGUE = {8,3,8,1},
    CLASS_SHAMAN = {21,4,21.5,2},
    CLASS_WARLOCK = {4,8,4.5,1},
    CLASS_WARRIOR = {8,2,8,2},
    FACTION_ALLIANCE = {13,1,13,1},
    FACTION_HORDE = {7.5,2,9,2},
    FACTION_NEUTRAL = {7,2,7,2},
    RACE_BLOODELF = {11,0,11,0},
    RACE_DARKIRONDWARF = {15,0,15,0},
    RACE_DRACTHYR = {8,3,8,3},
    RACE_DRAENEI = {4.5,0,5,1},
    RACE_DWARF = {12,1,12,1},
    RACE_EARTHENDWARF = {5,2,5,2},
    RACE_GNOME = {8,1,8,1},
    RACE_GOBLIN = {7,1,7,2},
    RACE_HARANIR = {12,3,12,3},
    RACE_HIGHMOUNTAINTAUREN = {10,3,10,2},
    RACE_HUMAN = {23,2,23,2},
    RACE_KULTIRAN = {13,1,13,1},
    RACE_LIGHTFORGEDDRAENEI = {3,3,3,2},
    RACE_MAGHARORC = {10.5,3,10.5,2},
    RACE_MECHAGNOME = {2,1,2,1},
    RACE_NIGHTBORNE = {15,0,15,0},
    RACE_NIGHTELF = {3,1,3,1},
    RACE_ORC = {11,4,11,2},
    RACE_PANDAREN = {4,3,3.5,1},
    RACE_SCOURGE = {1,12,2,6},
    RACE_TAUREN = {3,2,3,1},
    RACE_TROLL = {16,1,15.5,1},
    RACE_VOIDELF = {4,2,5,2},
    RACE_VULPERA = {6,3,5.5,2},
    RACE_WORGEN = {14,1,14,1},
    RACE_ZANDALARITROLL = {6,2,7,1},
}
J.CastBorderFitLimits = {0,0}
for id, inset in pairs(insets) do
    J.UnitSkinCatalog.entries[id].castInsets = inset
    J.CastBorderFitLimits[1] = math.max(J.CastBorderFitLimits[1],inset[1]+inset[3])
    J.CastBorderFitLimits[2] = math.max(J.CastBorderFitLimits[2],inset[2]+inset[4])
end
