-- Uses the exact runtime border pieces; no second set of fitting formulas.
local M=dofile("tests/mock_wow.lua");local J=M.load()
local function json(v)
    if type(v)=="string" then return '"'..v:gsub('\\','\\\\'):gsub('"','\\"'):gsub('\n','\\n')..'"' end
    if type(v)~="table" then return tostring(v) end
    local result={}
    for k,x in pairs(v) do result[#result+1]=json(tostring(k))..":"..json(x) end
    table.sort(result);return "{"..table.concat(result,",").."}"
end
local out={width=180,height=16,themes={}}
for id,entry in pairs(J.UnitSkinCatalog.entries) do
    local art=J.PortraitCatalog.entries[id]
    local theme={label=art.label,group=art.group,styles={},fittings={},file=entry.cast:match("([^\\]+)%.tga$")}
    for _,width in ipairs({50,75,100,125,150}) do for _,height in ipairs({50,75,100,125,150}) do
        theme.fittings[width.."x"..height]={CAPPED=J.CastBars:FitPieces(entry,180,16,1,1,false,width,height)}
    end end
    theme.styles.CAPPED=J.CastBars:Pieces(entry,180,16,1,1,false)
    out.themes[id]=theme
end
local f=assert(io.open("artwork/cast-bars/runtime-borders.js","w"));f:write("// Generated by tools/export_cast_preview.lua from Core/CastBars.lua\nwindow.castBorders=",json(out),";\n");f:close()
