-- Export the real registered theme to the browser preview, avoiding a second layout definition.
local M = dofile("tests/mock_wow.lua")
local J = M.load()
local function json(value)
    if type(value) == "string" then return string.format("%q",value) end
    if type(value) ~= "table" then return tostring(value) end
    local keys, fields = {}, {}
    for k in pairs(value) do keys[#keys+1] = k end
    table.sort(keys)
    for _, k in ipairs(keys) do fields[#fields+1] = json(k) .. ":" .. json(value[k]) end
    return "{" .. table.concat(fields,",") .. "}"
end
local output = assert(io.open("artwork/paladin-ret-review/runtime-layout.js","w"))
output:write("// Generated by tools/export_fit_preview.lua from the active theme.\nconst runtimeTheme = ",
    json(J.ThemeManager.registry.paladin_ret),";\n")
local reported=assert(io.open("artwork/paladin-ret-review/reported-fit-profile.txt")):read("*a"):gsub("%s+$","")
assert(J.ProfileManager:Import(reported))
local resolved={}
for _,key in ipairs(J.Core.order) do resolved[key]=J.ThemeManager:Resolve(key) end
output:write("const reportedTheme = ",json(resolved),";\n")
output:close()

local hub = assert(io.open("artwork/hubs/runtime-layout.js","w"))
hub:write("// Exported from the actual registered Lua fitting template.\nconst runtimeHub = ",json(J.ThemeManager.registry.paladin_ret.actionHub),";\n")
hub:close()
