"""Measure painted cast edges without rewriting any PNG or TGA artwork."""
import argparse
from pathlib import Path
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'Frostforge/Themes/CastBorders.lua'


def measure(path):
    with Image.open(path) as image:
        assert image.size == (512, 128), path
        alpha = np.asarray(image.convert('RGBA'))[:, :, 3]
    assert not alpha[48:80, 48:464].any(), path
    # Follow the solid rail, excluding isolated end ornaments and soft alpha.
    solid = alpha >= 128
    left = np.median([np.flatnonzero(solid[y, :48])[-1] + 1 for y in range(56, 72)])
    right = np.median([np.flatnonzero(solid[y, 464:])[0] + 464 for y in range(56, 72)])
    top = np.median([np.flatnonzero(solid[:48, x])[-1] + 1 for x in range(152, 360)])
    bottom = np.median([np.flatnonzero(solid[80:, x])[0] + 80 for x in range(152, 360)])
    return [48-left, 48-top, right-464, bottom-80]


def source():
    lines = ['local _, J = ...',
             '-- Generated by tools/measure_cast_borders.py; original artwork stays unchanged.',
             '-- Transparent inset from each shared slice boundary to the painted rail.',
             'local insets = {']
    for path in sorted((ROOT / 'Frostforge/Media/CastBars').glob('*.png')):
        values = ','.join(f'{value:g}' for value in measure(path))
        lines.append(f'    {path.stem.upper()} = {{{values}}},')
    lines.extend(['}', 'J.CastBorderFitLimits = {0,0}',
                  'for id, inset in pairs(insets) do',
                  '    J.UnitSkinCatalog.entries[id].castInsets = inset',
                  '    J.CastBorderFitLimits[1] = math.max(J.CastBorderFitLimits[1],inset[1]+inset[3])',
                  '    J.CastBorderFitLimits[2] = math.max(J.CastBorderFitLimits[2],inset[2]+inset[4])', 'end', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = source()
    if args.check:
        assert OUTPUT.read_text() == text, 'Cast edge measurements need refreshing'
    else:
        OUTPUT.write_text(text)
